name: My GitHub Actions Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Upgrade Dependencies
        run: npm update

      - name: Fix Prettier version
        run: npm uninstall prettier && npm install --save-dev prettier@latest

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: build-output
          path: dist/  # Adjust if your build folder has a different name

